# Basic LAMP stack

version: "2.1"

services:
  # Web
  web:
    hostname: web
    image: ${WEB_IMAGE}
    volumes:
      # Project root volume
      - project_root:/var/www:ro
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
    environment:
      - APACHE_DOCUMENTROOT=/var/www
    depends_on:
      - cli
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # DB
  db:
    hostname: db
    image: ${DB_IMAGE}
    ports:
      - "${MYSQL_PORT_MAPPING:-3306}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
    labels:
      - io.docksal.virtual-host=db.${VIRTUAL_HOST}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # CLI
  # Used for all console commands and tools.
  cli:
    hostname: cli
    image: ${CLI_IMAGE}
    volumes:
      # Project root volume
      - project_root:/var/www:rw
      # Host home volume (for SSH keys and other credentials).
      # host_home:/.home:ro
      # Shared ssh-agent socket
      - docksal_ssh_agent:/.ssh-agent:ro
    environment:
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Solr
#  solr:
#    hostname: solr
#    image: ${SOLR_IMAGE}
#    labels:
#      - io.docksal.virtual-host=solr.${VIRTUAL_HOST}
#    dns:
#      - ${DOCKSAL_DNS1}
#      - ${DOCKSAL_DNS2}
