#!/usr/bin/env bash

## Initialize a Docksal powered Drupal 8 site
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT is passed from fin.
# The following variables are configured in the '.env' file: DOCROOT, VIRTUAL_HOST.

SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
SITE_ENV="$@"
DATABASE_DIR="${SITEDIR_PATH}/db/"

if ${SITE_ENV}; then
    SITE_ENV="live";
fi


#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }


is_linux ()
{
	uname | grep 'Linux' >/dev/null
}

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo-green "Copying ${dest}..."
		cp $source $dest
	else
		echo-yellow "${dest} already in place."
	fi
}

create_temp_database_directory()
{
    if [[ ! -d "${SITEDIR_PATH}/db" ]]; then
		echo-green "Creating db folder in ${SITEDIR_PATH}/db..."
		mkdir "${DATABASE_DIR}"
	else
		echo-yellow "${DATABASE_DIR} already in place."
	fi
}

create_files_directory()
{
    if [[ ! -d "${SITEDIR_PATH}/files" ]]; then
		echo-green "Creating db folder in ${SITEDIR_PATH}/db..."
		mkdir "${SITEDIR_PATH}/files"
	else
		echo-yellow "${SITEDIR_PATH}/files already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------



# Fix file/folder permissions
fix_permissions ()
{
	echo-green "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

# Import database from Pantheon
import_database ()
{
    echo-green "Importing...";
    fin db import "${DATABASE_DIR}${PANTHEON_SITE}_${SITE_ENV}.sql";
    echo-green "Clearing caches...";
    fin drush cr;
}


#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

if [[ "$PROJECT_ROOT" == "" ]]; then
	echo-red "\$PROJECT_ROOT is not set"
	exit 1
fi

# Project initialization steps
echo -e "${green_bg} Step 1 ${NC}${green} Initializing local project configuration...${NC}"
fix_permissions


echo -e "${green_bg} Step 3 ${NC}${green} Database and files...${NC}"

create_temp_database_directory
time import_database


echo -en "${green_bg} DONE! ${NC} "
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."

#-------------------------- END: Execution --------------------------------
